version: "3.9"

services:
  json-validation-service:
    image: json-validation-service
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgres
  postgres:
    image: postgres:13.7-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
